<a href="https://colab.research.google.com/github/mikemwai/artificial_intelligence/blob/main/ML_task_one_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import the necessary libraries

In [ ]:
# Data Library
import pandas as pd

# Library for Matrices
import numpy as np

# Machine learning Libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import mean_squared_error

# Deep Learning Libraries
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

# Data Visualization Library
import matplotlib.pyplot as plt

# 1) Read CSV file & Create DataFrames

In [ ]:
# Store dataset in a Pandas Dataframe
df = pd.read_csv('Nairobi Office Price Ex.csv')
df

,LOC,FUR,AMB,PROX_SCH,PROX_ROAD,PROX_MALL,WATER,HK_SER,SIZE,PRICE
0,karen,yes,serene,no,yes,yes,yes,yes,32.502345,31.707006
1,madaraka,yes,semi_serene,yes,yes,yes,no,no,53.426804,68.777596
2,karen,no,noisy,no,yes,yes,yes,yes,61.530358,62.562382
3,karen,yes,semi_serene,no,no,no,yes,yes,47.475640,71.546632
4,buruburu,no,semi_serene,no,yes,yes,yes,yes,59.813208,87.230925
5,donholm,no,serene,no,no,yes,no,yes,55.142188,78.211518
6,langata,no,very_noisy,yes,yes,no,no,yes,52.211797,79.641973
7,langata,yes,serene,no,no,yes,yes,no,39.299567,59.171489
8,donholm,yes,semi_serene,yes,no,no,yes,no,48.105042,75.331242
9,karen,yes,serene,no,no,no,no,no,52.550014,71.300880
10,madaraka,yes,noisy,yes,yes,no,yes,yes,45.419730,55.165677
11,langata,no,semi_serene,yes,no,yes,yes,yes,54.351635,82.478847
12,buruburu,yes,semi_serene,yes,yes,no,no,no,44.164049,62.008923
13,karen,yes,semi_serene,yes,yes,yes,yes,yes,58.168471,75.392870

# 2) Encode the features

In [ ]:
# Encode the features
features = ['LOC', 'FUR', 'AMB', 'PROX_SCH', 'PROX_ROAD', 'PROX_MALL', 'WATER', 'HK_SER']
df = pd.get_dummies(df, columns=features)
df

,SIZE,PRICE,LOC_buruburu,LOC_donholm,LOC_karen,LOC_langata,LOC_madaraka,FUR_no,FUR_yes,AMB_noisy,...,PROX_SCH_no,PROX_SCH_yes,PROX_ROAD_no,PROX_ROAD_yes,PROX_MALL_no,PROX_MALL_yes,WATER_no,WATER_yes,HK_SER_no,HK_SER_yes
0,32.502345,31.707006,0,0,1,0,0,0,1,0,...,1,0,0,1,0,1,0,1,0,1
1,53.426804,68.777596,0,0,0,0,1,0,1,0,...,0,1,0,1,0,1,1,0,1,0
2,61.530358,62.562382,0,0,1,0,0,1,0,1,...,1,0,0,1,0,1,0,1,0,1
3,47.475640,71.546632,0,0,1,0,0,0,1,0,...,1,0,1,0,1,0,0,1,0,1
4,59.813208,87.230925,1,0,0,0,0,1,0,0,...,1,0,0,1,0,1,0,1,0,1
5,55.142188,78.211518,0,1,0,0,0,1,0,0,...,1,0,1,0,0,1,1,0,0,1
6,52.211797,79.641973,0,0,0,1,0,1,0,0,...,0,1,0,1,1,0,1,0,0,1
7,39.299567,59.171489,0,0,0,1,0,0,1,0,...,1,0,1,0,0,1,0,1,1,0
8,48.105042,75.331242,0,1,0,0,0,0,1,0,...,0,1,1,0,1,0,0,1,1,0
9,52.550014,71.300880,0,0,1,0,0,0,1,0,...,1,0,1,0,1,0,1,0,1,0
10,45.419730,55.165677,0,0,0,0,1,0,1,1,...,0,1,0,1,1,0,0,1,0,1
11,54.351635,82.478847,0,0,0,1,0,1,0,0,...,0,1,1,0,0,1,0,1,0,1
12,44.164049,62.008923,1,0,0,0,0,0,1,0,...,0,1,0,1,1,0,1,0,1,0
13,58.168471,75.392870,0,0,1,0,0,0,1,0,...,0,1,0,1,0,1,0,1,0,1

# 3) Data Training

In [ ]:
# Split the data into train and test sets
X = df.drop('PRICE', axis=1)
y = df['PRICE']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Scale the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train, X_test

(array([[-1.06592362,  2.12132034, -0.47140452, -0.61237244, -0.47140452,
         -0.47140452, -0.75592895,  0.75592895, -0.47140452,  0.91287093,
         -0.47140452, -0.31622777, -0.91287093,  0.91287093, -0.75592895,
          0.75592895,  1.09544512, -1.09544512,  1.32287566, -1.32287566,
          1.32287566, -1.32287566],
        [ 0.56443318, -0.47140452,  2.12132034, -0.61237244, -0.47140452,
         -0.47140452,  1.32287566, -1.32287566, -0.47140452, -1.09544512,
          2.12132034, -0.31622777,  1.09544512, -1.09544512,  1.32287566,
         -1.32287566, -0.91287093,  0.91287093,  1.32287566, -1.32287566,
         -0.75592895,  0.75592895],
        [-0.48064925, -0.47140452,  2.12132034, -0.61237244, -0.47140452,
         -0.47140452, -0.75592895,  0.75592895, -0.47140452,  0.91287093,
         -0.47140452, -0.31622777, -0.91287093,  0.91287093,  1.32287566,
         -1.32287566,  1.09544512, -1.09544512, -0.75592895,  0.75592895,
          1.32287566, -1.32287566],
        [ 1.5131364 , -0.47140452, -0.47140452,  1.63299316, -0.47140452,
         -0.47140452,  1.32287566, -1.32287566,  2.12132034, -1.09544512,
         -0.47140452, -0.31622777,  1.09544512, -1.09544512, -0.75592895,
          0.75592895, -0.91287093,  0.91287093, -0.75592895,  0.75592895,
         -0.75592895,  0.75592895],
        [ 0.30968247, -0.47140452, -0.47140452, -0.61237244, -0.47140452,
          2.12132034, -0.75592895,  0.75592895, -0.47140452,  0.91287093,
         -0.47140452, -0.31622777, -0.91287093,  0.91287093, -0.75592895,
          0.75592895, -0.91287093,  0.91287093,  1.32287566, -1.32287566,
          1.32287566, -1.32287566],
        [ 1.01386454, -0.47140452, -0.47140452,  1.63299316, -0.47140452,
         -0.47140452, -0.75592895,  0.75592895, -0.47140452,  0.91287093,
         -0.47140452, -0.31622777, -0.91287093,  0.91287093, -0.75592895,
          0.75592895, -0.91287093,  0.91287093, -0.75592895,  0.75592895,
         -0.75592895,  0.75592895],
        [ 1.25812346,  2.12132034, -0.47140452, -0.61237244, -0.47140452,
         -0.47140452,  1.32287566, -1.32287566, -0.47140452,  0.91287093,
         -0.47140452, -0.31622777,  1.09544512, -1.09544512, -0.75592895,
          0.75592895, -0.91287093,  0.91287093, -0.75592895,  0.75592895,
         -0.75592895,  0.75592895],
        [-1.78834504, -0.47140452, -0.47140452, -0.61237244,  2.12132034,
         -0.47140452, -0.75592895,  0.75592895, -0.47140452, -1.09544512,
          2.12132034, -0.31622777,  1.09544512, -1.09544512,  1.32287566,
         -1.32287566, -0.91287093,  0.91287093, -0.75592895,  0.75592895,
          1.32287566, -1.32287566],
        [-0.87944325, -0.47140452, -0.47140452, -0.61237244, -0.47140452,
          2.12132034, -0.75592895,  0.75592895,  2.12132034, -1.09544512,
         -0.47140452, -0.31622777, -0.91287093,  0.91287093, -0.75592895,
          0.75592895,  1.09544512, -1.09544512, -0.75592895,  0.75592895,
         -0.75592895,  0.75592895],
        [-0.57412137, -0.47140452, -0.47140452,  1.63299316, -0.47140452,
         -0.47140452, -0.75592895,  0.75592895, -0.47140452,  0.91287093,
         -0.47140452, -0.31622777,  1.09544512, -1.09544512,  1.32287566,
         -1.32287566,  1.09544512, -1.09544512, -0.75592895,  0.75592895,
         -0.75592895,  0.75592895],
        [ 0.12924247, -0.47140452, -0.47140452, -0.61237244,  2.12132034,
         -0.47140452,  1.32287566, -1.32287566, -0.47140452, -1.09544512,
         -0.47140452,  3.16227766, -0.91287093,  0.91287093, -0.75592895,
          0.75592895,  1.09544512, -1.09544512,  1.32287566, -1.32287566,
         -0.75592895,  0.75592895]]),
 array([[ 0.17947098, -0.47140452, -0.47140452,  1.63299316, -0.47140452,
         -0.47140452, -0.75592895,  0.75592895, -0.47140452, -1.09544512,
          2.12132034, -0.31622777,  1.09544512, -1.09544512,  1.32287566,
         -1.32287566,  1.09544512, -1.09544512,  1.32287566, -1.32287566,
          1.32287566, -1.32287566],
        [ 0.44702855, -0.47140452, -0.47140452, -0.61237244,  2.12132034,
         -0.47140452,  1.32287566, -1.32287566, -0.47140452,  0.91287093,
         -0.47140452, -0.31622777, -0.91287093,  0.91287093,  1.32287566,
         -1.32287566, -0.91287093,  0.91287093, -0.75592895,  0.75592895,
         -0.75592895,  0.75592895],
        [-2.7977963 , -0.47140452, -0.47140452,  1.63299316, -0.47140452,
         -0.47140452, -0.75592895,  0.75592895, -0.47140452, -1.09544512,
          2.12132034, -0.31622777,  1.09544512, -1.09544512, -0.75592895,
          0.75592895, -0.91287093,  0.91287093, -0.75592895,  0.75592895,
         -0.75592895,  0.75592895]]))

# 4) Artificial Neural Network Model

In [ ]:
# Define the model
model = Sequential()
model.add(Dense(32, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(1))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 32)                736

 dense_1 (Dense)             (None, 16)                528

 dense_2 (Dense)             (None, 1)                 17

=================================================================
Total params: 1281 (5.00 KB)
Trainable params: 1281 (5.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
model.compile(loss='mean_squared_error', optimizer='adam')

In [ ]:
# Train the model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=50, batch_size=32)

Epoch 1/50
1/1 [==============================] - 1s 1s/step - loss: 4968.8745 - val_loss: 4251.4175
Epoch 2/50
1/1 [==============================] - 0s 42ms/step - loss: 4961.7739 - val_loss: 4247.4165
Epoch 3/50
1/1 [==============================] - 0s 38ms/step - loss: 4954.4316 - val_loss: 4243.3354
Epoch 4/50
1/1 [==============================] - 0s 34ms/step - loss: 4947.0840 - val_loss: 4239.2217
Epoch 5/50
1/1 [==============================] - 0s 37ms/step - loss: 4939.7871 - val_loss: 4235.0708
Epoch 6/50
1/1 [==============================] - 0s 37ms/step - loss: 4932.6016 - val_loss: 4230.7661
Epoch 7/50
1/1 [==============================] - 0s 34ms/step - loss: 4925.4902 - val_loss: 4226.2798
Epoch 8/50
1/1 [==============================] - 0s 36ms/step - loss: 4918.3198 - val_loss: 4221.8169
Epoch 9/50
1/1 [==============================] - 0s 42ms/step - loss: 4911.0825 - val_loss: 4217.3257
Epoch 10/50
1/1 [==============================] - 0s 37ms/step - loss: 4903.8062 - val_loss: 4212.6362
Epoch 11/50
1/1 [==============================] - 0s 35ms/step - loss: 4896.5425 - val_loss: 4207.8267
Epoch 12/50
1/1 [==============================] - 0s 38ms/step - loss: 4889.5840 - val_loss: 4202.9185
Epoch 13/50
1/1 [==============================] - 0s 33ms/step - loss: 4882.6523 - val_loss: 4197.8438
Epoch 14/50
1/1 [==============================] - 0s 33ms/step - loss: 4875.7534 - val_loss: 4192.7412
Epoch 15/50
1/1 [==============================] - 0s 34ms/step - loss: 4868.6147 - val_loss: 4187.6343
Epoch 16/50
1/1 [==============================] - 0s 33ms/step - loss: 4861.3999 - val_loss: 4182.5249
Epoch 17/50
1/1 [==============================] - 0s 33ms/step - loss: 4854.1763 - val_loss: 4177.3896
Epoch 18/50
1/1 [==============================] - 0s 33ms/step - loss: 4846.8379 - val_loss: 4172.1245
Epoch 19/50
1/1 [==============================] - 0s 36ms/step - loss: 4839.4692 - val_loss: 4166.6841
Epoch 20/50
1/1 [==============================] - 0s 36ms/step - loss: 4832.0537 - val_loss: 4161.2236
Epoch 21/50
1/1 [==============================] - 0s 35ms/step - loss: 4824.5972 - val_loss: 4155.7651
Epoch 22/50
1/1 [==============================] - 0s 33ms/step - loss: 4817.1289 - val_loss: 4150.2046
Epoch 23/50
1/1 [==============================] - 0s 37ms/step - loss: 4809.6309 - val_loss: 4144.6606
Epoch 24/50
1/1 [==============================] - 0s 37ms/step - loss: 4802.0684 - val_loss: 4139.1138
Epoch 25/50
1/1 [==============================] - 0s 36ms/step - loss: 4794.4473 - val_loss: 4133.5327
Epoch 26/50
1/1 [==============================] - 0s 33ms/step - loss: 4786.7222 - val_loss: 4127.9229
Epoch 27/50
1/1 [==============================] - 0s 35ms/step - loss: 4778.9590 - val_loss: 4122.2642
Epoch 28/50
1/1 [==============================] - 0s 39ms/step - loss: 4771.1055 - val_loss: 4115.9985
Epoch 29/50
1/1 [==============================] - 0s 41ms/step - loss: 4763.1680 - val_loss: 4109.6357
Epoch 30/50
1/1 [==============================] - 0s 34ms/step - loss: 4755.1606 - val_loss: 4103.2437
Epoch 31/50
1/1 [==============================] - 0s 36ms/step - loss: 4747.0547 - val_loss: 4096.8594
Epoch 32/50
1/1 [==============================] - 0s 36ms/step - loss: 4738.8281 - val_loss: 4090.4473
Epoch 33/50
1/1 [==============================] - 0s 35ms/step - loss: 4730.4604 - val_loss: 4083.9971
Epoch 34/50
1/1 [==============================] - 0s 36ms/step - loss: 4721.9297 - val_loss: 4077.4910
Epoch 35/50
1/1 [==============================] - 0s 32ms/step - loss: 4713.2886 - val_loss: 4070.9229
Epoch 36/50
1/1 [==============================] - 0s 33ms/step - loss: 4704.5762 - val_loss: 4064.2910
Epoch 37/50
1/1 [==============================] - 0s 45ms/step - loss: 4695.7065 - val_loss: 4057.5637
Epoch 38/50
1/1 [==============================] - 0s 37ms/step - loss: 4686.5864 - val_loss: 4050.7461
Epoch 39/50
1/1 [==============================] - 0s 44ms/step - loss: 4677.2090 - val_loss: 4043.8420
Epoch 40/50
1/1 [==============================] - 0s 35ms/step - loss: 4667.6309 - val_loss: 4036.8396
Epoch 41/50
1/1 [==============================] - 0s 35ms/step - loss: 4657.8813 - val_loss: 4029.7786
Epoch 42/50
1/1 [==============================] - 0s 33ms/step - loss: 4647.9829 - val_loss: 4022.7053
Epoch 43/50
1/1 [==============================] - 0s 34ms/step - loss: 4637.9346 - val_loss: 4015.5486
Epoch 44/50
1/1 [==============================] - 0s 33ms/step - loss: 4627.7822 - val_loss: 4008.2981
Epoch 45/50
1/1 [==============================] - 0s 35ms/step - loss: 4617.4043 - val_loss: 4000.9563
Epoch 46/50
1/1 [==============================] - 0s 35ms/step - loss: 4606.9199 - val_loss: 3993.5330
Epoch 47/50
1/1 [==============================] - 0s 68ms/step - loss: 4596.3291 - val_loss: 3985.9578
Epoch 48/50
1/1 [==============================] - 0s 55ms/step - loss: 4585.5239 - val_loss: 3978.2869
Epoch 49/50
1/1 [==============================] - 0s 66ms/step - loss: 4574.5122 - val_loss: 3970.0159
Epoch 50/50
1/1 [==============================] - 0s 65ms/step - loss: 4563.3179 - val_loss: 3961.6113

In [ ]:
# Evaluate the model
y_pred = model.predict(X_test)
print(f'MSE: {mean_squared_error(y_test, y_pred)}')

1/1 [==============================] - 0s 82ms/step
MSE: 3961.6110580478435

# 5) Price Prediction

In [ ]:
# Predict the office price when the size is 100 sq. ft.
size_100 = np.full((1, X_train.shape[1]), 0)
size_100[0][-1] = (100 - scaler.mean_[-1]) / np.sqrt(scaler.var_[-1])
price_100 = model.predict(size_100)
print(f'The predicted office price when the size is 100 sq. ft. is Ksh {price_100[0][0]}')

1/1 [==============================] - 0s 57ms/step
The predicted office price when the size is 100 sq. ft. is Ksh 110.30482482910156